apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: haste
spec:
  replicas: 1
  serviceName: haste
  {{ if .Values.haste.volume }}
  volumeClaimTemplates:
  - metadata:
      name: {{ required "must provide a volume name" .Values.haste.volume.name }}
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: {{ required "must provide a volume size" .Values.haste.volume.size }}
  {{ end }}
  template:
    metadata:
      labels:
        app: haste
    spec:
      containers:
      - name: haste
        image: {{ required "must provide a docker repository" .Values.haste.repository }}/{{ .Values.haste.image }}:{{ .Values.haste.tag }}
        env:
        - name: PORT
          value: '80'
        - name: HOST
          value: '0.0.0.0'
        - name: STORAGE_TYPE
          value: '{{ .Values.haste.storage.type }}'
        - name: STORAGE_PATH
          value: '{{ .Values.haste.storage.path }}'
        resources:
          limits:
            memory: 256Mi
            cpu: 0.3
          requests:
            memory: 128Mi
            cpu: 0.1
        {{ if .Values.haste.volume }}
        volumeMounts:
        - name: {{ required "must provide a volume name" .Values.haste.volume.name }}
          mountPath: {{ required "must provide a storage path" .Values.haste.storage.path }}
        {{ end }}
        imagePullPolicy: Always
      restartPolicy: Always
